CREATE TABLE "hospitals" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "supported_languages" jsonb,
  "default_session_type" varchar,
  "his_mapping_config" jsonb
);

CREATE TABLE "physicians" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hospital_id" integer NOT NULL,
  "name" varchar,
  "role" varchar,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "patients" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hospital_id" integer NOT NULL,
  "abha_id" varchar UNIQUE,
  "is_guest" boolean DEFAULT false,
  "name" varchar,
  "dob" date,
  "gender" varchar,
  "preferred_language" varchar,
  "accessibility_settings" jsonb
);

CREATE TABLE "consents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" integer NOT NULL,
  "consent_type" varchar,
  "granted_at" timestamp NOT NULL
);

CREATE TABLE "clinical_sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" integer NOT NULL,
  "type" varchar,
  "status" varchar,
  "red_flag_triggered" boolean DEFAULT false,
  "queue_ticket" varchar,
  "his_sync_status" varchar,
  "abha_sync_status" varchar,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "clinical_summaries" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" integer UNIQUE NOT NULL,
  "hpi_json" jsonb,
  "ayush_json" jsonb,
  "physician_notes" text,
  "diagnosis" text,
  "treatment_plan" text,
  "revisit_date" date,
  "summary_status" varchar,
  "reviewed_by" integer,
  "patient_confirmed_at" timestamp,
  "confirmed_at" timestamp
);

CREATE TABLE "summary_versions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "summary_id" integer NOT NULL,
  "version_number" integer NOT NULL,
  "content" jsonb NOT NULL,
  "edited_by" integer,
  "edited_at" timestamp NOT NULL
);

CREATE TABLE "documents" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" integer NOT NULL,
  "storage_url" varchar NOT NULL,
  "ocr_status" varchar,
  "raw_ocr_text" text,
  "confirmed_text" text,
  "verified_by_patient" boolean DEFAULT false,
  "uploaded_at" timestamp NOT NULL
);

CREATE TABLE "lab_values" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "document_id" integer NOT NULL,
  "test_name" varchar NOT NULL,
  "value" varchar,
  "status" varchar
);

CREATE TABLE "refresh_tokens" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" integer,
  "physician_id" integer,
  "token_hash" varchar NOT NULL,
  "issued_at" timestamp NOT NULL,
  "expires_at" timestamp NOT NULL,
  "revoked" boolean DEFAULT false
);

CREATE TABLE "audit_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "actor_id" integer NOT NULL,
  "actor_type" varchar NOT NULL,
  "action" varchar NOT NULL,
  "target_table" varchar NOT NULL,
  "target_id" integer NOT NULL,
  "timestamp" timestamp NOT NULL
);

ALTER TABLE "physicians" ADD FOREIGN KEY ("hospital_id") REFERENCES "hospitals" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "patients" ADD FOREIGN KEY ("hospital_id") REFERENCES "hospitals" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "consents" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "clinical_sessions" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "clinical_summaries" ADD FOREIGN KEY ("session_id") REFERENCES "clinical_sessions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "clinical_summaries" ADD FOREIGN KEY ("reviewed_by") REFERENCES "physicians" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "summary_versions" ADD FOREIGN KEY ("summary_id") REFERENCES "clinical_summaries" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "summary_versions" ADD FOREIGN KEY ("edited_by") REFERENCES "physicians" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "documents" ADD FOREIGN KEY ("session_id") REFERENCES "clinical_sessions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lab_values" ADD FOREIGN KEY ("document_id") REFERENCES "documents" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "refresh_tokens" ADD FOREIGN KEY ("patient_id") REFERENCES "patients" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "refresh_tokens" ADD FOREIGN KEY ("physician_id") REFERENCES "physicians" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "refresh_tokens" ADD CONSTRAINT chk_refresh_token_owner
  CHECK (
    (patient_id IS NOT NULL AND physician_id IS NULL)
    OR
    (patient_id IS NULL AND physician_id IS NOT NULL)
  );
  
CREATE INDEX idx_patients_abha_id ON patients(abha_id);
CREATE INDEX idx_sessions_status ON clinical_sessions(status);
CREATE INDEX idx_sessions_red_flag ON clinical_sessions(red_flag_triggered);